name: DSPlugin
main: dsPlugin.DSPlugin
description: CraftBukkit Geometry Plugin (of sorts)
author: Action0Jackson, GandalfsShoe
version: 0.9.0

commands:
   encase:
      description: Encases user in specified material.
      usage: /<command> <player> <outermaterial> [innerMaterial]
      permission: DSPlugin.encase
      permission-message: You don't have <permission>
   square:
      description: Creates a square of the specified material.
      usage: /<command> <x> <y> <z> <xyzlength> <material>
      permission: DSPlugin.square
      permission-message: You don't have <permission>      
   cube:
      description: Creates a cube of the specified material types.
      usage: /<command> <x> <y> <z> <xzlength> <outerMaterial> [innerMaterial]
      permission: DSPlugin.cube
      permission-message: You don't have <permission>
   rectangle:
      description: Creates a rectangle of the specified material.
      usage: /<command> <x> <y> <z> <xLength> <zLength> <material>
      permission: DSPlugin.rectangle
      permission-message: You don't have <permission>            
   cuboid:
      description: Creates a cuboid of the specified material types.
      usage: /<command> <x> <y> <z> <xLength> <yLength> <zLength> <outerMaterial> [innerMaterial]
      permission: DSPlugin.cuboid
      permission-message: You don't have <permission>
   pyramid:
      description: Creates a pyramid of the specified material and size.
      usage: /<command> <x> <y> <z> <baseLength> <outerMaterial> [innerMaterial]
      permission: DSPlugin.pyramid
      permission-message: You don't have <permission>
   circle:
      description: Creates a circle of the specified material types.
      usage: /<command> <x> <y> <z> <radius> <material>
      permission: DSPlugin.circle
      permission-message: You don't have <permission>      
   sphere:
      description: Creates a sphere of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <radius> <outermaterial> [innerMaterial] [maxTh] [maxPhi]
      permission: DSPlugin.sphere
      permission-message: You don't have <permission>
   tunnel:
      description: Creates a minecart tunnel of specified size starting at x,y,z.
      usage: /<command> <x> <y> <z> <y-length-direction(N,S,E,W)> [y-length-direction(N,S,E,W)]...
      permission: DSPlugin.tunnel
      permission-message: You don't have <permission>
   cone:
      description: Create a cone of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <height> <radius1> <radius2> <outermaterial> [innerMaterial]
      permission: DSPlugin.cone
      permission-message: You don't have <permission>  
   cylinder:
      description: Create a cylinder of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <height> <radius> <outermaterial> [innerMaterial]
      permission: DSPlugin.cylinder
      permission-message: You don't have <permission>   
   pyramid2:
      description: Creates a pyramid of the specified material and size with center at x,y,z.  Negative radius will generate an inverted pyramid.
      usage: /<command> <x> <y> <z> <radius> <outerMaterial> [innerMaterial]
      permission: DSPlugin.pyramid2
      permission-message: You don't have <permission>  
   octahedron:
      description: Creates an octahedron of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <radius> <outerMaterial> [innerMaterial]
      permission: DSPlugin.octahedron
      permission-message: You don't have <permission>
   ellipsoid:
      description: Creates an ellipsoid of the specified material and size.
      usage: /<command> <x> <y> <z> <a> <b> <c> <outerMaterial> [innerMaterial] [maxTh] [maxPhi]
      permission: DSPlugin.ellipsoid
      permission-message: You don't have <permission>
      
permissions:
   DSPlugin.*:
     description: Gives access to all DSPlugin commands
     default: true
     children:
       DSPlugin.encase: true
       DSPlugin.square: true
       DSPlugin.cube: true
       DSPlugin.rectangle: true
       DSPlugin.circle: true
       DSPlugin.cuboid: true
       DSPlugin.pyramid: true
       DSPlugin.sphere: true
       DSPlugin.tunnel: true
       DSPlugin.cone: true
       DSPlugin.cylinder: true
       DSPlugin.pyramid2: true
       DSPlugin.octahedron: true
       DSPlugin.ellipsoid: true
   DSPlugin.encase:
     description: Allows you to encase another player in specified material
     default: true
   DSPlugin.square:
     description: Allows you to create a square of specified material
     default: true
   DSPlugin.cube:
     description: Allows you to create a cube of specified material
     default: true
   DSPlugin.rectangle:
     description: Allows you to create a rectangle of specified material
     default: true
   DSPlugin.circle:
     description: Allows you to create a circle of specified material
     default: true
   DSPlugin.cuboid:
     description: Allows you to create a cuboid of specified material
     default: true
   DSPlugin.pyramid:
     description: Allows you to create a pyramid of specified material
     default: true
   DSPlugin.sphere:
     description: Allows you to create a sphere of specified material
     default: true
   DSPlugin.tunnel:
     description: Allows you to create a minecart tunnel
     default: true
   DSPlugin.cone:
     description: Allows you to create a cone of specified material
     default: true     
   DSPlugin.cylinder:
     description: Allows you to create a cylinder of specified material
     default: true
   DSPlugin.pyramid2:
     description: Allows you to create a pyramid of specified material
     default: true
   DSPlugin.octahedron:
     description: Allows you to create an octahedron of specified material
     default: true
   DSPlugin.ellipsoid:
     description: Allows you to create an ellipsoid of specified material
     default: true 
      