name: Geometry
main: geometry.Geometry
description: CraftBukkit Geometry Plugin 
author: Action0Jackson, GandalfsShoe
version: 1.0.0

commands:
   encase:
      description: Encases user in specified material.
      usage: /<command> <player> <outermaterial> [innerMaterial]
      permission: Geometry.encase
      permission-message: You don't have <permission>
   square:
      description: Creates a square of the specified material.
      usage: /<command> <x> <y> <z> <xyzlength> <material>
      permission: Geometry.square
      permission-message: You don't have <permission>      
   cube:
      description: Creates a cube of the specified material types.
      usage: /<command> <x> <y> <z> <xzlength> <outerMaterial> [innerMaterial]
      permission: Geometry.cube
      permission-message: You don't have <permission>
   rectangle:
      description: Creates a rectangle of the specified material.
      usage: /<command> <x> <y> <z> <xLength> <zLength> <material>
      permission: Geometry.rectangle
      permission-message: You don't have <permission>            
   cuboid:
      description: Creates a cuboid of the specified material types.
      usage: /<command> <x> <y> <z> <xLength> <yLength> <zLength> <outerMaterial> [innerMaterial]
      permission: Geometry.cuboid
      permission-message: You don't have <permission>
   pyramid:
      description: Creates a pyramid of the specified material and size.
      usage: /<command> <x> <y> <z> <baseLength> <outerMaterial> [innerMaterial]
      permission: Geometry.pyramid
      permission-message: You don't have <permission>
   circle:
      description: Creates a circle of the specified material types.
      usage: /<command> <x> <y> <z> <radius> <material>
      permission: Geometry.circle
      permission-message: You don't have <permission>      
   sphere:
      description: Creates a sphere of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <radius> <outermaterial> [innerMaterial] [maxTh] [maxPhi]
      permission: Geometry.sphere
      permission-message: You don't have <permission>
   tunnel:
      description: Creates a minecart tunnel of specified size starting at x,y,z.
      usage: /<command> <x> <y> <z> <y-length-direction(N,S,E,W)> [y-length-direction(N,S,E,W)]...
      permission: Geometry.tunnel
      permission-message: You don't have <permission>
   cone:
      description: Create a cone of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <height> <radius1> <radius2> <outermaterial> [innerMaterial]
      permission: Geometry.cone
      permission-message: You don't have <permission>  
   cylinder:
      description: Create a cylinder of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <height> <radius> <outermaterial> [innerMaterial]
      permission: Geometry.cylinder
      permission-message: You don't have <permission>   
   pyramid2:
      description: Creates a pyramid of the specified material and size with center at x,y,z.  Negative radius will generate an inverted pyramid.
      usage: /<command> <x> <y> <z> <radius> <outerMaterial> [innerMaterial]
      permission: Geometry.pyramid2
      permission-message: You don't have <permission>  
   octahedron:
      description: Creates an octahedron of the specified material and size with center at x,y,z.
      usage: /<command> <x> <y> <z> <radius> <outerMaterial> [innerMaterial]
      permission: Geometry.octahedron
      permission-message: You don't have <permission>
   ellipsoid:
      description: Creates an ellipsoid of the specified material and size.
      usage: /<command> <x> <y> <z> <a> <b> <c> <outerMaterial> [innerMaterial] [maxTh] [maxPhi]
      permission: Geometry.ellipsoid
      permission-message: You don't have <permission>
   ellipse:
      description: Creates an ellipse of the specified material and size.
      usage: /<command> <x> <y> <z> <a> <c> <material>
      permission: Geometry.ellipse
      permission-message: You don't have <permission>
      
permissions:
   Geometry.*:
     description: Gives access to all Geometry commands
     default: true
     children:
       Geometry.encase: true
       Geometry.square: true
       Geometry.cube: true
       Geometry.rectangle: true
       Geometry.circle: true
       Geometry.cuboid: true
       Geometry.pyramid: true
       Geometry.sphere: true
       Geometry.tunnel: true
       Geometry.cone: true
       Geometry.cylinder: true
       Geometry.pyramid2: true
       Geometry.octahedron: true
       Geometry.ellipsoid: true
       Geometry.ellipse: true
   Geometry.encase:
     description: Allows you to encase another player in specified material
     default: true
   Geometry.square:
     description: Allows you to create a square of specified material
     default: true
   Geometry.cube:
     description: Allows you to create a cube of specified material
     default: true
   Geometry.rectangle:
     description: Allows you to create a rectangle of specified material
     default: true
   Geometry.circle:
     description: Allows you to create a circle of specified material
     default: true
   Geometry.cuboid:
     description: Allows you to create a cuboid of specified material
     default: true
   Geometry.pyramid:
     description: Allows you to create a pyramid of specified material
     default: true
   Geometry.sphere:
     description: Allows you to create a sphere of specified material
     default: true
   Geometry.tunnel:
     description: Allows you to create a minecart tunnel
     default: true
   Geometry.cone:
     description: Allows you to create a cone of specified material
     default: true     
   Geometry.cylinder:
     description: Allows you to create a cylinder of specified material
     default: true
   Geometry.pyramid2:
     description: Allows you to create a pyramid of specified material
     default: true
   Geometry.octahedron:
     description: Allows you to create an octahedron of specified material
     default: true
   Geometry.ellipsoid:
     description: Allows you to create an ellipsoid of specified material
     default: true
   Geometry.ellipse:
     description: Allows you to create an ellipse of specified material
     default: true  
      